spring:
  datasource:
    username: root
    password: Shreyas@2003
    url: jdbc:mysql://localhost:3306/emp_database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true